package hibernate;
// Generated 26-may-2014 12:54:18 by Hibernate Tools 3.6.0



/**
 * Ciudades generated by hbm2java
 */
public class Ciudades  implements java.io.Serializable {


     private String nombre;

    public Ciudades() {
    }

    public Ciudades(String nombre) {
       this.nombre = nombre;
    }
   
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


}


