package hibernate;
// Generated 26-may-2014 12:54:18 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones  implements java.io.Serializable {


     private Integer idPublicacion;
     private String nick;
     private int idVehiculo;
     private String nombre_ciudad;
     private String nombre_universidad;
     private String descripcion;
     private Date fecha;
     private String hora;

    public Publicaciones() {
    }

    public Publicaciones(String nick, int idVehiculo, String nombre_ciudad, String nombre_universidad, String descripcion, Date fecha, String hora) {
       this.nick = nick;
       this.idVehiculo = idVehiculo;
       this.nombre_ciudad = nombre_ciudad;
       this.nombre_universidad = nombre_universidad;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdPublicacion() {
        return this.idPublicacion;
    }
    
    public void setIdPublicacion(Integer idPublicacion) {
        this.idPublicacion = idPublicacion;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getNombre_ciudad() {
        return this.nombre_ciudad;
    }
    
    public void setNombre_ciudad(String nombre_ciudad) {
        this.nombre_ciudad = nombre_ciudad;
    }
    public String getNombre_universidad() {
        return this.nombre_universidad;
    }
    
    public void setNombre_universidad(String nombre_universidad) {
        this.nombre_universidad = nombre_universidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


