package hibernate;
// Generated 26-may-2014 12:54:18 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones  implements java.io.Serializable {


     private Integer idPublicacion;
     private String nick;
     private int idVehiculo;
     private int idCiudad;
     private int idUniversidad;
     private String descripcion;
     private Date fecha;
     private String hora;

    public Publicaciones() {
    }

    public Publicaciones(String nick, int idVehiculo, int idCiudad, int idUniversidad, String descripcion, Date fecha, String hora) {
       this.nick = nick;
       this.idVehiculo = idVehiculo;
       this.idCiudad = idCiudad;
       this.idUniversidad = idUniversidad;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdPublicacion() {
        return this.idPublicacion;
    }
    
    public void setIdPublicacion(Integer idPublicacion) {
        this.idPublicacion = idPublicacion;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public int getIdUniversidad() {
        return this.idUniversidad;
    }
    
    public void setIdUniversidad(int idUniversidad) {
        this.idUniversidad = idUniversidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


