package hibernate;
// Generated 27-may-2014 21:52:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones  implements java.io.Serializable {


     private Integer idPublicacion;
     private String nick;
     private int idVehiculo;
     private String nombreCiudad;
     private String nombreUniversidad;
     private String descripcion;
     private Date fecha;
     private String hora;

    public Publicaciones() {
    }

    public Publicaciones(String nick, int idVehiculo, String nombreCiudad, String nombreUniversidad, String descripcion, Date fecha, String hora) {
       this.nick = nick;
       this.idVehiculo = idVehiculo;
       this.nombreCiudad = nombreCiudad;
       this.nombreUniversidad = nombreUniversidad;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdPublicacion() {
        return this.idPublicacion;
    }
    
    public void setIdPublicacion(Integer idPublicacion) {
        this.idPublicacion = idPublicacion;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public String getNombreUniversidad() {
        return this.nombreUniversidad;
    }
    
    public void setNombreUniversidad(String nombreUniversidad) {
        this.nombreUniversidad = nombreUniversidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


