package hibernate;
// Generated 27-may-2014 21:52:51 by Hibernate Tools 3.6.0



/**
 * Universidades generated by hbm2java
 */
public class Universidades  implements java.io.Serializable {


     private String nombre;

    public Universidades() {
    }

    public Universidades(String nombre) {
       this.nombre = nombre;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


