package hibernate;
// Generated 26-may-2014 12:54:18 by Hibernate Tools 3.6.0



/**
 * Universidades generated by hbm2java
 */
public class Universidades  implements java.io.Serializable {


     private Integer idUniversidad;
     private String nombre;

    public Universidades() {
    }

    public Universidades(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdUniversidad() {
        return this.idUniversidad;
    }
    
    public void setIdUniversidad(Integer idUniversidad) {
        this.idUniversidad = idUniversidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


