package hibernate;
// Generated 26-may-2014 12:54:18 by Hibernate Tools 3.6.0



/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private String nick;
     private String marca;
     private String modelo;
     private String descripcion;

    public Vehiculo() {
    }

    public Vehiculo(String nick, String marca, String modelo, String descripcion) {
       this.nick = nick;
       this.marca = marca;
       this.modelo = modelo;
       this.descripcion = descripcion;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


